"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.supplierRouter = void 0;
const express_1 = require("express");
const SupplierController_1 = require("../../controller/SupplierController");
exports.supplierRouter = (0, express_1.Router)();
exports.supplierRouter.get('/suppliers', SupplierController_1.getSuppliers);
exports.supplierRouter.get('/suppliers/active', SupplierController_1.getActiveSuppliers);
exports.supplierRouter.get('/suppliers/:id', SupplierController_1.getSupplierById);
exports.supplierRouter.post('/suppliers', SupplierController_1.createSupplier);
exports.supplierRouter.put('/suppliers/:id', SupplierController_1.updateSupplier);
exports.supplierRouter.delete('/suppliers/:id', SupplierController_1.deleteSupplier);
